"use client";

import * as React from "react";
import { useState, useEffect, Suspense } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { PlusCircle, Edit, Trash2, Search, X, Package, Radio } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/services/api";
import { useAuth } from "@/lib/auth-context";
import { useSearchParams } from "next/navigation";

function IOTDashboardContent() {
  const { token } = useAuth();
  const searchParams = useSearchParams();
  const tabParam = searchParams.get("tab");
  const [activeTab, setActiveTab] = useState("gateways");

  useEffect(() => {
    if (tabParam === "end_devices" || tabParam === "gateways") {
      setActiveTab(tabParam);
    }
  }, [tabParam]);

  // State for Gateways
  const [gateways, setGateways] = useState<any[]>([]);
  const [tenants, setTenants] = useState<any[]>([]);
  const [gatewaySearch, setGatewaySearch] = useState("");
  const [isGatewayDialogOpen, setIsGatewayDialogOpen] = useState(false);
  const [editingGateway, setEditingGateway] = useState<any>(null);
  const [gatewayForm, setGatewayForm] = useState({
    tenant_name: "",
    gateway_name: "",
    gateway_ID: "",
    application_name: "",
    application_description: "",
    application_tags: "",
    gateway_stats_interval: "30",
  });

  // State for End Devices
  const [endDevices, setEndDevices] = useState<any[]>([]);
  const [deviceSearch, setDeviceSearch] = useState("");
  const [isDeviceDialogOpen, setIsDeviceDialogOpen] = useState(false);
  const [editingDevice, setEditingDevice] = useState<any>(null);
  const [deviceForm, setDeviceForm] = useState({
    end_device_name: "",
    end_device_ID: "",
    maximum_bus: 1,
    fota_update_version: "v1.0.0",
    address: "",
  });

  useEffect(() => {
    loadGateways();
    loadEndDevices();
    loadTenants();
  }, [token]);

  const loadTenants = async () => {
    try {
      // Clients are used as Tenants in IOT Implementation
      const data = await api.clients.getAll();
      setTenants(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error("Failed to load tenants:", error);
    }
  };

  const loadGateways = async () => {
    if (!token) return;
    try {
      const data = await api.gateway.getAll(token);
      setGateways(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error("Failed to load gateways:", error);
      toast.error("Failed to load gateways");
    }
  };

  const loadEndDevices = async () => {
    if (!token) return;
    try {
      const data = await api.end_device.getAll(token);
      setEndDevices(Array.isArray(data) ? data : []);
    } catch (error) {
      console.error("Failed to load devices:", error);
      toast.error("Failed to load devices");
    }
  };

  // Gateway Handlers
  const handleGatewaySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingGateway) {
        await api.gateway.update(editingGateway.id, gatewayForm, token || "");
        toast.success("Gateway updated successfully");
      } else {
        // gateway_ID is auto-generated by backend
        const { gateway_ID, ...submissionData } = gatewayForm;
        await api.gateway.create(submissionData, token || "");
        toast.success("Gateway created successfully");
      }
      setIsGatewayDialogOpen(false);
      loadGateways();
    } catch (error: any) {
      toast.error(error.message || "Failed to save gateway");
    }
  };

  const handleEditGateway = (gateway: any) => {
    setEditingGateway(gateway);
    setGatewayForm({
      tenant_name: gateway.tenant_name || "",
      gateway_name: gateway.gateway_name,
      gateway_ID: gateway.gateway_ID,
      application_name: gateway.application_name,
      application_description: gateway.application_description || "",
      application_tags: gateway.application_tags || "",
      gateway_stats_interval: gateway.gateway_stats_interval || "30",
    });
    setIsGatewayDialogOpen(true);
  };

  const handleDeleteGateway = async (id: number) => {
    if (confirm("Are you sure?")) {
      try {
        await api.gateway.delete(id, token || "");
        toast.success("Gateway deleted");
        loadGateways();
      } catch (error) {
        toast.error("Failed to delete gateway");
      }
    }
  };

  // End Device Handlers
  const handleDeviceSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingDevice) {
        await api.end_device.update(editingDevice.id, deviceForm, token || "");
        toast.success("End Device updated successfully");
      } else {
        // end_device_ID is auto-generated by backend
        const { end_device_ID, ...submissionData } = deviceForm;
        await api.end_device.create(submissionData, token || "");
        toast.success("End Device created successfully");
      }
      setIsDeviceDialogOpen(false);
      loadEndDevices();
    } catch (error: any) {
      toast.error(error.message || "Failed to save device");
    }
  };

  const handleEditDevice = (device: any) => {
    setEditingDevice(device);
    setDeviceForm({
      end_device_name: device.end_device_name,
      end_device_ID: device.end_device_ID,
      maximum_bus: device.maximum_bus,
      fota_update_version: device.fota_update_version || "v1.0.0",
      address: device.address || "",
    });
    setIsDeviceDialogOpen(true);
  };

  const handleDeleteDevice = async (id: number) => {
    if (confirm("Are you sure?")) {
      try {
        await api.end_device.delete(id, token || "");
        toast.success("End Device deleted");
        loadEndDevices();
      } catch (error) {
        toast.error("Failed to delete device");
      }
    }
  };

  const filteredGateways = gateways.filter(g =>
    g.gateway_name?.toLowerCase().includes(gatewaySearch.toLowerCase()) ||
    g.gateway_ID?.toLowerCase().includes(gatewaySearch.toLowerCase())
  );

  const filteredDevices = endDevices.filter(d =>
    d.end_device_name?.toLowerCase().includes(deviceSearch.toLowerCase()) ||
    d.end_device_ID?.toLowerCase().includes(deviceSearch.toLowerCase())
  );

  return (
    <div className="space-y-6 p-4">
      <div className="flex items-center justify-between">
        <h1 className="text-3xl font-bold tracking-tight">IOT Infrastructure Management</h1>
      </div>

      <Tabs value={activeTab} className="w-full" onValueChange={setActiveTab}>
        <TabsList className="grid w-[400px] grid-cols-2">
          <TabsTrigger value="gateways" className="flex items-center gap-2">
            <Radio className="h-4 w-4" />
            Gateways
          </TabsTrigger>
          <TabsTrigger value="end_devices" className="flex items-center gap-2">
            <Package className="h-4 w-4" />
            End Devices
          </TabsTrigger>
        </TabsList>

        {/* ============================================================================
            GATEWAYS TAB
        ============================================================================ */}
        <TabsContent value="gateways" className="space-y-4 pt-4">
          <div className="flex items-center justify-between gap-4">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search gateways..."
                value={gatewaySearch}
                onChange={(e) => setGatewaySearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Button onClick={() => { setEditingGateway(null); setGatewayForm({ tenant_name: "", gateway_name: "", gateway_ID: "", application_name: "", application_description: "", application_tags: "", gateway_stats_interval: "30" }); setIsGatewayDialogOpen(true); }}>
              <PlusCircle className="mr-2 h-4 w-4" />
              Add Gateway
            </Button>
          </div>

          <div className="rounded-md border bg-card">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Gateway ID</TableHead>
                  <TableHead>Name</TableHead>
                  <TableHead>Application</TableHead>
                  <TableHead>Stats Interval</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredGateways.length === 0 ? (
                  <TableRow><TableCell colSpan={5} className="text-center py-8 text-muted-foreground">No gateways found</TableCell></TableRow>
                ) : (
                  filteredGateways.map((g) => (
                    <TableRow key={g.id}>
                      <TableCell className="font-mono text-xs">{g.gateway_ID}</TableCell>
                      <TableCell className="font-medium">{g.gateway_name}</TableCell>
                      <TableCell>{g.application_name}</TableCell>
                      <TableCell>{g.gateway_stats_interval}s</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button variant="ghost" size="icon" onClick={() => handleEditGateway(g)}><Edit className="h-4 w-4" /></Button>
                          <Button variant="ghost" size="icon" onClick={() => handleDeleteGateway(g.id)} className="text-destructive"><Trash2 className="h-4 w-4" /></Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </TabsContent>

        {/* ============================================================================
            END DEVICES TAB
        ============================================================================ */}
        <TabsContent value="end_devices" className="space-y-4 pt-4">
          <div className="flex items-center justify-between gap-4">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search devices..."
                value={deviceSearch}
                onChange={(e) => setDeviceSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Button onClick={() => { setEditingDevice(null); setDeviceForm({ end_device_name: "", end_device_ID: "", maximum_bus: 1, fota_update_version: "v1.0.0", address: "" }); setIsDeviceDialogOpen(true); }}>
              <PlusCircle className="mr-2 h-4 w-4" />
              Add End Device
            </Button>
          </div>

          <div className="rounded-md border bg-card">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Device ID</TableHead>
                  <TableHead>Name</TableHead>
                  <TableHead>Max Bus</TableHead>
                  <TableHead>FOTA Version</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredDevices.length === 0 ? (
                  <TableRow><TableCell colSpan={5} className="text-center py-8 text-muted-foreground">No devices found</TableCell></TableRow>
                ) : (
                  filteredDevices.map((d) => (
                    <TableRow key={d.id}>
                      <TableCell className="font-mono text-xs">{d.end_device_ID}</TableCell>
                      <TableCell className="font-medium">{d.end_device_name}</TableCell>
                      <TableCell>{d.maximum_bus}</TableCell>
                      <TableCell>{d.fota_update_version}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end gap-2">
                          <Button variant="ghost" size="icon" onClick={() => handleEditDevice(d)}><Edit className="h-4 w-4" /></Button>
                          <Button variant="ghost" size="icon" onClick={() => handleDeleteDevice(d.id)} className="text-destructive"><Trash2 className="h-4 w-4" /></Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </TabsContent>
      </Tabs>

      {/* Gateway Dialog */}
      <Dialog open={isGatewayDialogOpen} onOpenChange={setIsGatewayDialogOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>{editingGateway ? "Edit Gateway" : "Add Gateway"}</DialogTitle>
            <DialogDescription>Gateway & Application registration</DialogDescription>
          </DialogHeader>
          <form onSubmit={handleGatewaySubmit} className="space-y-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="tenant_name">Tenant</Label>
              <Select
                value={gatewayForm.tenant_name}
                onValueChange={(val) => setGatewayForm({ ...gatewayForm, tenant_name: val })}
                required
              >
                <SelectTrigger id="tenant_name">
                  <SelectValue placeholder="Select Tenant" />
                </SelectTrigger>
                <SelectContent>
                  {tenants.map((t) => (
                    <SelectItem key={t.id} value={t.client_name}>{t.client_name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="gateway_name">Gateway Name</Label>
              <Input id="gateway_name" value={gatewayForm.gateway_name} onChange={(e) => setGatewayForm({ ...gatewayForm, gateway_name: e.target.value })} placeholder="Roof HQ Gateway" required />
            </div>
            {editingGateway && (
              <div className="grid gap-2">
                <Label htmlFor="gateway_ID">Gateway ID</Label>
                <Input id="gateway_ID" value={gatewayForm.gateway_ID} disabled placeholder="GW-001" />
              </div>
            )}
            <div className="grid gap-2">
              <Label htmlFor="application_name">Application Name</Label>
              <Input id="application_name" value={gatewayForm.application_name} onChange={(e) => setGatewayForm({ ...gatewayForm, application_name: e.target.value })} placeholder="Smart Factory" required />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="gateway_stats_interval">Stats Interval (s)</Label>
                <Input id="gateway_stats_interval" value={gatewayForm.gateway_stats_interval} onChange={(e) => setGatewayForm({ ...gatewayForm, gateway_stats_interval: e.target.value })} placeholder="30" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="application_tags">Tags</Label>
                <Input id="application_tags" value={gatewayForm.application_tags} onChange={(e) => setGatewayForm({ ...gatewayForm, application_tags: e.target.value })} placeholder="factory, production" />
              </div>
            </div>
            <DialogFooter>
              <Button type="submit">{editingGateway ? "Save Changes" : "Register Gateway"}</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>

      {/* Device Dialog */}
      <Dialog open={isDeviceDialogOpen} onOpenChange={setIsDeviceDialogOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>{editingDevice ? "Edit End Device" : "Add End Device"}</DialogTitle>
            <DialogDescription>End device registration and configuration</DialogDescription>
          </DialogHeader>
          <form onSubmit={handleDeviceSubmit} className="space-y-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="end_device_name">Device Name</Label>
              <Input id="end_device_name" value={deviceForm.end_device_name} onChange={(e) => setDeviceForm({ ...deviceForm, end_device_name: e.target.value })} placeholder="Temperature Sensor A" required />
            </div>
            {editingDevice && (
              <div className="grid gap-2">
                <Label htmlFor="end_device_ID">Device ID</Label>
                <Input id="end_device_ID" value={deviceForm.end_device_ID} disabled placeholder="ED-001" />
              </div>
            )}
            <div className="grid grid-cols-2 gap-4">
              <div className="grid gap-2">
                <Label htmlFor="maximum_bus">Maximum Bus</Label>
                <Input id="maximum_bus" type="number" value={deviceForm.maximum_bus} onChange={(e) => setDeviceForm({ ...deviceForm, maximum_bus: parseInt(e.target.value) })} />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="fota_update_version">FOTA Version</Label>
                <Input id="fota_update_version" value={deviceForm.fota_update_version} onChange={(e) => setDeviceForm({ ...deviceForm, fota_update_version: e.target.value })} />
              </div>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="address">Installation Address</Label>
              <Textarea id="address" value={deviceForm.address} onChange={(e) => setDeviceForm({ ...deviceForm, address: e.target.value })} placeholder="Factory Floor 1, Section B" />
            </div>
            <DialogFooter>
              <Button type="submit">{editingDevice ? "Save Changes" : "Register Device"}</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default function IOTDashboardPage() {
  return (
    <Suspense fallback={<div>Loading Dashboard...</div>}>
      <IOTDashboardContent />
    </Suspense>
  );
}
